version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    # Si tienes variables, crea backend/.env y descomenta:
    # env_file:
    #   - backend/.env
    ports:
      - "8000:8000"
    networks:
      - webnet

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
